### ISSUE TITLE
Failure to launch app

### ISSUE THREAD

**Issue by jasikpark** [sunrise-choir/sunrise-social#2]
I'm not sure if this is meant to be able to run reliably yet, but I tried to launch the dev app on my machine.

<img width="811" alt="image" src="https://user-images.githubusercontent.com/10626596/124161756-68cfd300-da63-11eb-8f67-9d9ef2ada922.png">

To Reproduce:
1. Clone the repo
2. Run `yarn`
3. Run `yarn dev`
4. Get the above image when the electron app tries to start but cannot find `main.js`

**Comment by ahdinosaur** [comment]
hi @jasikpark, thanks for reaching out.

on your first run, electron is expected to error at first until `dist/main.js` is built by webpack, then should succeed. does it error and quit? my expectation is that it should error but `electronmon` will wait for changes and then reload.

otherwise, you can run `yarn build` to do an initial build, then run `yarn dev`.

**Comment by ahdinosaur** [comment]
even if it does work as i described, obviously this is confusing, so we should either make a note in the README or find a better way (this is the least bad way i was able to come up with).

**Comment by jasikpark** [comment]
Yeah, maybe at least make a point in the instructions:
1. `yarn`
2. `yarn build`
3. `yarn dev`

**Comment by jasikpark** [comment]
I got that popup and it just said that it would continue running, waiting for changes.

**Comment by jasikpark** [comment]
```
yarn build
yarn run v1.22.10
$ yarn build:graphql-codegen && yarn:build:webpack
$ graphql-codegen --config graphql-codegen.yml
  ✔ Parse configuration
  ✔ Generate outputs
/bin/sh: yarn:build:webpack: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

👀

**Comment by jasikpark** [comment]
`"build": "yarn build:graphql-codegen && yarn:build:webpack",` is this meant to read `yarn:build:webpack` or `yarn build:webpack`?

I've found https://www.npmjs.com/package/npm-run-all indispensable.

**Comment by jasikpark** [comment]
It looks like that change works.
